### ISSUE TITLE
Version 1.14 

### ISSUE THREAD

**Issue by wrongspot** [buckaroo-it/Shopware-plugin#12]
Are you really serious, version 1.14 is only available for SW 5.7? Version 1.13 is completely broken.

**Comment by Buckaroo-Rens** [comment]
@wrongspot Not sure if this is the right way of communicating. Little more detail on why 1.13 is broken for you would be nice. Apart from that: 1.14 should also work on older versions.

**Comment by Buckaroo-Rens** [comment]
@wrongspot Not sure if this is the right way of communicating. 

But correct, 1.14 is only available for 5.7+ since this is already 1,5 years old so it's very hard to keep support on version older then that (5.6 = 2,5 years old). Could you please clarify what goes wrong for you.

**Comment by wrongspot** [comment]
5.7.0 is from 14 June 2021 (https://github.com/shopware/shopware/releases/tag/v5.7.0), thats not 1,5 years. is never 1 year old. Unfortunately, some customers cannot simply upgrade the shop. This can cost the customer a lot of money. Is your payment plugin really broken until 5.6?

**Comment by Buckaroo-Rens** [comment]
@wrongspot https://github.com/shopware/shopware/releases/tag/v5.7.0-RC1 -> First code was from nov 2020. But again. Please, could you let us know in more detail what goes wrong for you on 5.6 then we can specifically look into it. You must understand that we are happy to help but we need more info then 'completely broken'. Do you get any errors, do you have any logs etc.

**Comment by wrongspot** [comment]
Hello, we can't install the plugin right now in an official way. At this point https://github.com/buckaroo-it/Shopware_5/blob/1.14.0/plugin.xml#L23 your plugin requires hard min shopware 5.7.x

In an SW 5.6.x Shop we get this error if we try to update to version 1.14 via composer.
![Bildschirmfoto 2022-02-10 um 15 51 09](https://user-images.githubusercontent.com/907458/153553683-8876b5cf-6913-4003-bbb0-4ee66b868db8.png)

So, it would be really great, when 1.14 not break version until 5.6 to allow `<compatibility minVersion="5.6.0"/>` at this point. 

Ok, one step back. The real Problem on Version 1.13. is, that has minimum stability to shopware  5.6.0. 
https://github.com/buckaroo-it/Shopware_5/blob/1.13.0/plugin.xml#L23

But you try to call at this point https://github.com/buckaroo-it/Shopware_5/blob/1.13.0/Components/Base/AbstractPaymentController.php#L623 
`Shopware()->Session()->save()`  but in SW 5.6 `Shopware()->Session()` is Class `\Enlight_Components_Session_Namespace` and extends from `Zend_Session_Namespace` and there is no `->save()` Method.  in an 5.6 Shop you get the following error. 
 
```
https://xxx.com/nl/nl/buckaroo_mastercard/pay_return?session_id=qn223p7jbipagqd1nouf1uqvs1&shop_id=9

Fatal error: Uncaught Error: Call to undefined method Enlight_Components_Session_Namespace::save() in /var/www/clients/client1/web12/web/deployer/releases/52/custom/plugins/BuckarooPayment/Components/Base/AbstractPaymentController.php:623 Stack trace: #0 /var/www/clients/client1/web12/web/deployer/releases/52/custom/plugins/BuckarooPayment/Components/Base/SimplePaymentController.php(571): BuckarooPayment\Components\Base\AbstractPaymentController->restoreSession('qn223p7jbipagqd...') #1 /var/www/clients/client1/web12/web/deployer/releases/52/vendor/shopware/shopware/engine/Library/Enlight/Controller/Action.php(192): BuckarooPayment\Components\Base\SimplePaymentController->payReturnAction() #2 /var/www/clients/client1/web12/web/deployer/releases/52/vendor/shopware/shopware/engine/Library/Enlight/Controller/Dispatcher/Default.php(478): Enlight_Controller_Action->dispatch('payReturnAction') #3 /var/www/clients/client1/web12/web/deployer/releases/52/vendor/shopware/shopware/engine/Library/Enlight/Controller/Front.php(228): Enl in /var/www/clients/client1/web12/web/deployer/releases/52/custom/plugins/BuckarooPayment/Components/Base/AbstractPaymentController.php on line 623
```
hope that helps

**Comment by Buckaroo-Rens** [comment]
@wrongspot  We are starting to look into this as from next week. Thanks for your input, very helpfull.
